# Generated by Django 5.2.8 on 2026-01-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('actions_taken', models.TextField(blank=True, null=True)),
                ('vitals', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
