# Generated by Django 6.0.1 on 2026-01-10 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Symptoms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='file',
        ),
        migrations.AddField(
            model_name='symptom',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 10, 14, 36, 55, 412773)),
            preserve_default=False,
        ),
    ]
