# Generated by Django 6.0.1 on 2026-01-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Symptoms', '0002_remove_symptom_file_symptom_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
